### ISSUE TITLE
matplotlib as requirements

### ISSUE THREAD

**Issue by aaronkl** [amzn/emukit#100]
If I install emukit via pip, matplotlib won't be install. However, it seems that it is a requirement of GPy (at least if I do `from emukit.test_functions import forrester_function` it throws me an error "ImportError: No module named 'matplotlib'" somewhere in GPy).

Could we add matplotlib to requirements.txt?

**Comment by apaleyes** [comment]
Ideally we shouldn't. Just because GPy messed up its dependencies does not mean Emukit also needs to do so. Especially since Emukit does not depend on matplotlib explicitly.

However I can understand that it can be a painful installation process. So as a compromise we could consider requiring some extra stuff for GPy. [Here](https://github.com/SheffieldML/GPy/blob/devel/setup.py#L167) I can see that matplotlib is declared as plotting extra requirement. So our requirements.txt could have something like 

    GPy=>123123 [plotting]

Would you be willing to try this change and submit a PR with it?

**Comment by aaronkl** [comment]
sure I can do that. However, I've just seen that in requirements/test_requirements.txt matplotlib will be explicitly installed. Should we also change that?

**Comment by apaleyes** [comment]
Thanks!

In testing we can be much more relaxed, as regular users will never need these dependencies. But if you implement that change, the line you found in test_reqs will become obsolete and can be removed.

To be honest, before today I didn't even know GPy had matplotlib as extra req

**Comment by apaleyes** [comment]
Merged
