### ISSUE TITLE
Discrete space optimization

### ISSUE THREAD

**Issue by dekuenstle** [amzn/emukit#169]
There are already discrete and categorical parameters in emukit, but gradient-based acquisition-optimization seems not optimal for such spaces. 
Are there plans for other optimizers like local search?
Probably additional optimizers would require additional features of the parameter space (e.g. value neighbourhood, transform vector encoding to parameter values, inverse transform, …). 

What are your thoughts about this?

Cheers 
David

**Comment by apaleyes** [comment]
As far as I remember, we don't have immediate plans for implementing other optimizers. That may come later, but are not working on anything that requires them at the moment. That said, of course we won't oppose a PR implementing that.

As for parameter space functionality to support specific optimizer, i personally think, unless these parameter manipulations are super general, should be done inside the optimizer itself. But that's just a general thought, specific cases might differ.

**Comment by marpulli** [comment]
I definitely agree that optimizers that treat discrete/categorical parameters properly would be a great addition to emukit. I don't know a lot about the different optimizers we could use or the required additional features you mention. 

Are the transforms required anything like the ones we have implemented in `emukit.core.encodings`? They don't currently have inverse transforms implemented, but that seems like a reasonable addition to these classes.

**Comment by aaronkl** [comment]
AFAIK, the most people use some stochastic local search variants to optimize the acquisition function in discrete spaces (see [here](https://ml.informatik.uni-freiburg.de/papers/11-LION5-SMAC.pdf) for example). I think we could fairly easily implement such as local search method as following:

1. get a starting configuration and the maximum number of steps as input
2. compute the neighborhood of the starting configuration by flipping each element while keeping all other elements of the configuration fix
3. for each neighbor compute the acquisition value
4. if we reached the maximum number of steps or we haven't improved upon our starting point return the starting point  otherwise replace the starting point with the best neighbor and repeat with step 2.

The only somewhat challenging part here is to compute the neighbors. For categorical parameters we could simply encode them first as a one-hot-encoding vector and randomly replace one 0 by 1. For ordinal or integer parameters we would need to change it to the next higher / lower value.
So I guess we could use `emukit.core.encoding` for that, we would just need another function that transforms them back into a Parameter object.
