### ISSUE TITLE
Problems extending BQ to higher dimensions + more complex integrals

### ISSUE THREAD

**Issue by tjdodwell** [amzn/emukit#269]
Hi,

Speaking to Neil he said this would be a good place to post a technical question. It is more about my lack of knowledge rather than a software issue, so if you would like it posted else where let me know :)

I have been playing around with Bayesian Quadrature in emukit (and using GPy to build my emulator). I have two questions

**(1) Extending to High Dimensions with 'ARD' kernels.**

I follow your worked example for the 1D_Hennig function. This works great! For my application I have a 4 dimesnional input space, so I have build a GP model in GPy

```
kernel = GPy.kern.RBF(input_dim=4,ARD=True)
m = GPy.models.GPRegression(X,Y,kernel)
m.optimize(messages=True)
```

When I try and do BQ I get an error

```
/usr/local/lib/python3.7/site-packages/emukit/quadrature/kernels/quadrature_rbf.py in qKq(self)
     74         erf_term = erf(diff_bounds_scaled) * diff_bounds_scaled * np.sqrt(np.pi)
     75 
---> 76         return np.float(prefac * (exp_term + erf_term).prod())
     77 
     78     # the following methods are gradients of a quadrature kernel

TypeError: only size-1 arrays can be converted to Python scalars
```

This is becuase I am using ARD Squared Exponential Kernel. Is there a way around this? With some digging in your code base I can't see an example or a different class to use. Or do I need to hack it, by rescaling my problem in each of the dimensions? Then retraining an isotropic kernel?

**(2) BQ for more complex integral.**

In the application I am looking at I actually want to do a more complex integral so if f(x) is my integrand which is expensive to compute, I also have a functional r(x) ( in my case a multivariant Gaussian) which is fast to compute, I want to do BQ on 

I = \int f(x)r(x)dx

This is the setting laid out by O'Hagan in his BQ paper. Is there an example of this?

Thanks in advance for your help!

Best

Tim Dodwell
Turing & Exeter

**Comment by mmahsereci** [comment]
Hi Tim,

yes, the github issues are a good place for this. 

1) You are right, the error occurs because you are using ARD=True in the GPy kernel. The quadrature kernel in emukit currently only support a scalar lengthscale for multi-D problems (ARD=False). One way around it for now would be to do a change of variables as you suggest (see also [here](https://en.wikipedia.org/wiki/Integration_by_substitution#Substitution_for_multiple_variables)). 
A more direct way would be to implement the appropriate QuadratureRBF (see 2) also since master branch diverged a bit from stable branch). 

2) The example you posted suggests that you are using the stable branch. There is more functionality in the master branch and it might be better for you to work with the master branch (even though it might be changing slightly.) 
The master branch contains integration of the RBF kernel against the standard Lebesgue measure, the multivariate isotropic Gaussian measure, and the multivariate uniform measure. It currently does not support integration against a multivariate Gaussian with a non-scalar covariance though. In case your integration measure is a Gaussian with non-scalar covariance, a (not so pretty but fast) way around this is to reformulate your problem as \int r(x)f(x)/p(x) dp(x) where p(x) is a multivariate Gaussian with scalar covariance. Then you would model r(x)f(x)/p(x) with a GP and integrate against p(x).

Currently there is no tutorial notebook which shows how to do the integration against a probability measure, but I'll post some example code below soon. 

Thanks,
Maren

**Comment by mmahsereci** [comment]
here are some code example that might work for you. they will work with master branch only. Dummy function here to make code work.

```
import numpy as np
import GPy
from emukit.core.loop.user_function import UserFunctionWrapper

def dummy_func(x):
    return np.ones([x.shape[0], 1])

user_function = UserFunctionWrapper(dummy_func)

D = 3 # dimensionality
N = 4 # number of initial observations

# initial observations
X_init = np.reshape(np.random.randn(N * D), [N, D])
Y_init = user_function.f(X_init)

# GPy model
gpy_model = GPy.models.GPRegression(X=X_init, Y=Y_init, kernel=GPy.kern.RBF(input_dim=D))

```

Then chose the appropriate measure and kernel.
```
from emukit.model_wrappers.gpy_quadrature_wrappers import BaseGaussianProcessGPy, RBFGPy
from emukit.quadrature.kernels.integration_measures import IsotropicGaussianMeasure
from emukit.quadrature.kernels import QuadratureRBFIsoGaussMeasure
from emukit.quadrature.methods.vanilla_bq import VanillaBayesianQuadrature
from emukit.quadrature.loop.quadrature_loop import VanillaBayesianQuadratureLoop

# Gaussian integration measure
measure = IsotropicGaussianMeasure(mean=np.zeros(D), variance=2.)

# wrap GPy model in emukit
emukit_qrbf = QuadratureRBFIsoGaussMeasure(RBFGPy(gpy_model.kern), measure)
emukit_gp = BaseGaussianProcessGPy(emukit_qrbf, gpy_model)
emukit_model = VanillaBayesianQuadrature(emukit_gp, X=X_init, Y=Y_init)
emukit_loop = VanillaBayesianQuadratureLoop(emukit_model)

# run the loop 
emukit_loop.run_loop(user_function, stopping_condition=20)

# intgerate the model
integral_mean, integral_var = emukit_loop.model.integrate()
```
Hope that helps,
Thanks,
Maren

**Comment by tjdodwell** [comment]
Thanks Maren! That is super!

**Comment by mmahsereci** [comment]
This seems to be resolved. I am closing the issue.
